<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TaskWise.Domain\TaskWise.Domain.csproj" />
  </ItemGroup>
</Project>
